-- PostgreSQL 17+. Instalacion NUEVA y atomica; no modifica tablas preexistentes.
BEGIN;
CREATE SCHEMA IF NOT EXISTS farmacia;
SET LOCAL search_path = farmacia, pg_catalog;

CREATE FUNCTION normalizar_texto(text) RETURNS text
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
SET search_path = pg_catalog
AS $$ SELECT lower(translate($1, 'ÁÉÍÓÚÜÑáéíóúüñ', 'AEIOUUNaeiouun')) $$;

CREATE TABLE usuario (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  nombres VARCHAR(100) NOT NULL,
  apellido_paterno VARCHAR(100) NOT NULL,
  apellido_materno VARCHAR(100) NULL,
  ci VARCHAR(20) NOT NULL,
  ci_extencion VARCHAR(10) NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL,
  user_name VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255)   NOT NULL,
  role VARCHAR(20)  NOT NULL DEFAULT 'Bioquimico',
  activo smallint NOT NULL DEFAULT 1,
  must_change_password smallint NOT NULL DEFAULT 1,
  fecha_registro timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_actualizacion timestamptz NULL DEFAULT NULL,
  id_usuario INT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_usuario_editor FOREIGN KEY (id_usuario) REFERENCES usuario(id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT ck_usuario_activo CHECK (activo IN (0,1)),
  CONSTRAINT ck_usuario_cambio_password CHECK (must_change_password IN (0,1)),
  CONSTRAINT ck_usuario_rol CHECK (role IN ('Admin','Bioquimico')),
  CONSTRAINT ck_usuario_email CHECK (CHAR_LENGTH(TRIM(email)) > 0),
  CONSTRAINT ck_usuario_nombre_login CHECK (CHAR_LENGTH(TRIM(user_name)) > 0),
  CONSTRAINT ck_usuario_password CHECK (CHAR_LENGTH(password_hash) >= 60)
);

CREATE TABLE usuario_token (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  usuario_idusuario INT NOT NULL,
  token_hash CHAR(64)   NOT NULL,
  tipo_token VARCHAR(45)   NOT NULL,
  fecha_creacion timestamptz NOT NULL,
  fecha_expiracion timestamptz NOT NULL,
  revocado smallint NOT NULL DEFAULT 0,
  usado smallint NOT NULL DEFAULT 0,
  fecha_uso timestamptz NULL,
  fecha_revocacion timestamptz NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_token_usuario FOREIGN KEY (usuario_idusuario) REFERENCES usuario(id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT ck_token_revocado CHECK (revocado IN (0,1)),
  CONSTRAINT ck_token_usado CHECK (usado IN (0,1)),
  CONSTRAINT ck_token_expiracion CHECK (fecha_expiracion > fecha_creacion),
  CONSTRAINT ck_token_hash CHECK (CHAR_LENGTH(token_hash) = 64),
  CONSTRAINT ck_token_tipo CHECK (CHAR_LENGTH(TRIM(tipo_token)) > 0)
);

CREATE TABLE clasificacion (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(45) NOT NULL,
  origen VARCHAR(45) NOT NULL,
  descripcion VARCHAR(100) NOT NULL,
  estado smallint NOT NULL DEFAULT 1,
  fecha_registro timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_actualizacion timestamptz NULL DEFAULT NULL,
  id_usuario INT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_clasificacion_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT ck_clasificacion_estado CHECK (estado IN (0,1)),
  CONSTRAINT ck_clasificacion_nombre CHECK (CHAR_LENGTH(TRIM(nombre)) BETWEEN 3 AND 45)
);

CREATE TABLE cliente (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  nit VARCHAR(20) NOT NULL,
  razon_social VARCHAR(45) NOT NULL,
  correo_electronico VARCHAR(45) NULL,
  estado smallint NOT NULL DEFAULT 1,
  fecha_registro timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_actualizacion timestamptz NULL DEFAULT NULL,
  id_usuario INT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_cliente_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT ck_cliente_estado CHECK (estado IN (0,1)),
  CONSTRAINT ck_cliente_nit CHECK (CHAR_LENGTH(TRIM(nit)) > 0),
  CONSTRAINT ck_cliente_razon CHECK (CHAR_LENGTH(TRIM(razon_social)) > 0)
);

CREATE TABLE medicamento (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR(100) NOT NULL,
  presentacion VARCHAR(100) NOT NULL,
  id_clasificacion INT NOT NULL,
  concentracion VARCHAR(100) NOT NULL,
  precio DECIMAL(12,2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  estado smallint NOT NULL DEFAULT 1,
  fecha_registro timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_actualizacion timestamptz NULL DEFAULT NULL,
  id_usuario INT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_medicamento_clasificacion FOREIGN KEY (id_clasificacion) REFERENCES clasificacion(id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_medicamento_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT ck_medicamento_precio CHECK (precio > 0 AND precio <= 1000),
  CONSTRAINT ck_medicamento_stock CHECK (stock >= 0),
  CONSTRAINT ck_medicamento_estado CHECK (estado IN (0,1)),
  CONSTRAINT ck_medicamento_nombre CHECK (CHAR_LENGTH(TRIM(nombre)) BETWEEN 3 AND 100)
);

CREATE TABLE venta (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  fecha_hora timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  total DECIMAL(18,2) NOT NULL,
  metodo_pago VARCHAR(45) NOT NULL,
  cliente_idcliente INT NOT NULL,
  usuario_idusuario INT NOT NULL,
  nit VARCHAR(20) NOT NULL,
  razon_social VARCHAR(45) NOT NULL,
  estado smallint NOT NULL DEFAULT 1,
  fecha_registro timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultima_actualizacion timestamptz NULL DEFAULT NULL,
  id_usuario_editor INT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_venta_cliente FOREIGN KEY (cliente_idcliente) REFERENCES cliente(id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_venta_usuario FOREIGN KEY (usuario_idusuario) REFERENCES usuario(id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_venta_editor FOREIGN KEY (id_usuario_editor) REFERENCES usuario(id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT ck_venta_total CHECK (total > 0),
  CONSTRAINT ck_venta_estado CHECK (estado IN (0,1)),
  CONSTRAINT ck_venta_pago CHECK (CHAR_LENGTH(TRIM(metodo_pago)) > 0)
);

CREATE TABLE detalle_venta (
  id_venta INT NOT NULL,
  id_medicamento INT NOT NULL,
  cantidad INT NOT NULL,
  precio_unitario DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (id_venta, id_medicamento),
  CONSTRAINT fk_detalle_venta FOREIGN KEY (id_venta) REFERENCES venta(id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT fk_detalle_medicamento FOREIGN KEY (id_medicamento) REFERENCES medicamento(id) ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE,
  CONSTRAINT ck_detalle_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_detalle_precio CHECK (precio_unitario > 0)
);

CREATE INDEX ix_usuario_activo_nombre ON usuario (activo, nombres, apellido_paterno);
CREATE INDEX ix_usuario_rol_activo ON usuario (role, activo);
CREATE INDEX ix_usuario_documento ON usuario (ci, ci_extencion);
CREATE INDEX ix_token_usuario_tipo_estado ON usuario_token (usuario_idusuario, tipo_token, revocado, usado);
CREATE INDEX ix_token_expiracion ON usuario_token (fecha_expiracion);
CREATE INDEX ix_token_uso ON usuario_token (usado, fecha_uso);
CREATE INDEX ix_token_revocacion ON usuario_token (revocado, fecha_revocacion);
CREATE INDEX ix_clasificacion_estado_nombre ON clasificacion (estado, nombre);
CREATE INDEX ix_cliente_estado_razon ON cliente (estado, razon_social);
CREATE INDEX ix_medicamento_estado_nombre ON medicamento (estado, nombre);
CREATE INDEX ix_medicamento_clasificacion_estado ON medicamento (id_clasificacion, estado);
CREATE INDEX ix_venta_estado_fecha ON venta (estado, fecha_hora);
CREATE INDEX ix_venta_cliente_fecha ON venta (cliente_idcliente, fecha_hora);
CREATE INDEX ix_venta_usuario_fecha ON venta (usuario_idusuario, fecha_hora);
CREATE INDEX ix_detalle_medicamento ON detalle_venta (id_medicamento);

CREATE UNIQUE INDEX uq_usuario_email ON usuario(normalizar_texto(email));
CREATE UNIQUE INDEX uq_usuario_user_name ON usuario(normalizar_texto(user_name));
CREATE UNIQUE INDEX uq_usuario_token_hash ON usuario_token(token_hash);
CREATE UNIQUE INDEX uq_clasificacion_nombre_activo ON clasificacion(normalizar_texto(nombre)) WHERE estado=1;
CREATE UNIQUE INDEX uq_cliente_nit_activo ON cliente(normalizar_texto(nit)) WHERE estado=1 AND upper(nit)<>'CF';

CREATE TABLE auditoria (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 fecha_utc timestamptz NOT NULL DEFAULT clock_timestamp(),
 tabla varchar(64) NOT NULL,
 operacion varchar(16) NOT NULL CHECK (operacion IN ('INSERT','UPDATE','DELETE','BAJA_LOGICA','REACTIVACION')),
 clave_registro jsonb NOT NULL,
 usuario_app_id integer CHECK (usuario_app_id>0),
 origen_actor varchar(24) NOT NULL,
 usuario_db varchar(288) NOT NULL,
 conexion_id bigint NOT NULL,
 solicitud_id varchar(64), motivo varchar(255),
 datos_anteriores jsonb, datos_nuevos jsonb,
 credencial_modificada smallint NOT NULL DEFAULT 0
);
CREATE INDEX ix_auditoria_tabla_fecha ON auditoria(tabla,fecha_utc);
CREATE INDEX ix_auditoria_actor_fecha ON auditoria(usuario_app_id,fecha_utc);
CREATE INDEX ix_auditoria_solicitud ON auditoria(solicitud_id);

-- Historial MySQL preservado íntegro, separado del historial de la nueva base.
CREATE TABLE auditoria_legacy_mysql (id bigint PRIMARY KEY, registro jsonb NOT NULL);

CREATE FUNCTION registrar_auditoria() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, farmacia AS $$
DECLARE
 anterior jsonb; nuevo jsonb; clave jsonb; operacion text := TG_OP;
 actor integer := NULLIF(current_setting('app.usuario_id',true),'')::integer;
 cambio smallint := 0;
BEGIN
 IF TG_OP <> 'INSERT' THEN anterior := to_jsonb(OLD); END IF;
 IF TG_OP <> 'DELETE' THEN nuevo := to_jsonb(NEW); END IF;
 IF TG_OP='UPDATE' THEN
   IF coalesce(anterior->>'activo',anterior->>'estado')='1'
      AND coalesce(nuevo->>'activo',nuevo->>'estado')='0' THEN operacion:='BAJA_LOGICA';
   ELSIF coalesce(anterior->>'activo',anterior->>'estado')='0'
      AND coalesce(nuevo->>'activo',nuevo->>'estado')='1' THEN operacion:='REACTIVACION'; END IF;
   IF anterior->>'password_hash' IS DISTINCT FROM nuevo->>'password_hash' THEN cambio:=1; END IF;
 END IF;
 IF TG_TABLE_NAME='detalle_venta' THEN
   clave:=jsonb_build_object('id_venta',coalesce(nuevo,anterior)->'id_venta','id_medicamento',coalesce(nuevo,anterior)->'id_medicamento');
 ELSE clave:=jsonb_build_object('id',coalesce(nuevo,anterior)->'id'); END IF;
 INSERT INTO farmacia.auditoria(tabla,operacion,clave_registro,usuario_app_id,origen_actor,usuario_db,
 conexion_id,solicitud_id,motivo,datos_anteriores,datos_nuevos,credencial_modificada)
 VALUES(TG_TABLE_NAME,operacion,clave,actor,CASE WHEN actor IS NULL THEN 'SIN_CONTEXTO' ELSE 'CONTEXTO_SESION' END,
 session_user,pg_backend_pid(),left(NULLIF(current_setting('app.solicitud_id',true),''),64),
 left(NULLIF(current_setting('app.motivo',true),''),255),
 anterior - 'password_hash' - 'token_hash',nuevo - 'password_hash' - 'token_hash',cambio);
 RETURN NULL;
END $$;
REVOKE ALL ON FUNCTION registrar_auditoria() FROM PUBLIC;

CREATE FUNCTION actualizar_fecha() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog AS $$
BEGIN NEW.ultima_actualizacion:=CURRENT_TIMESTAMP; RETURN NEW; END $$;
CREATE FUNCTION impedir_cambio_auditoria() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog AS $$
BEGIN RAISE EXCEPTION 'El historial de auditoria es inmutable'; END $$;
CREATE TRIGGER tr_auditoria_inmutable BEFORE UPDATE OR DELETE OR TRUNCATE ON auditoria
FOR EACH STATEMENT EXECUTE FUNCTION impedir_cambio_auditoria();
CREATE TRIGGER tr_legacy_inmutable BEFORE UPDATE OR DELETE OR TRUNCATE ON auditoria_legacy_mysql
FOR EACH STATEMENT EXECUTE FUNCTION impedir_cambio_auditoria();

DO $$ DECLARE tabla text; BEGIN
 FOREACH tabla IN ARRAY ARRAY['usuario','usuario_token','cliente','clasificacion','medicamento','venta','detalle_venta'] LOOP
 EXECUTE format('CREATE TRIGGER tr_%I_auditoria AFTER INSERT OR UPDATE OR DELETE ON farmacia.%I FOR EACH ROW EXECUTE FUNCTION farmacia.registrar_auditoria()',tabla,tabla);
 END LOOP;
 FOREACH tabla IN ARRAY ARRAY['usuario','cliente','clasificacion','medicamento','venta'] LOOP
 EXECUTE format('CREATE TRIGGER tr_%I_fecha BEFORE UPDATE ON farmacia.%I FOR EACH ROW EXECUTE FUNCTION farmacia.actualizar_fecha()',tabla,tabla);
 END LOOP;
END $$;

CREATE VIEW vw_auditoria_stock AS
SELECT id AS id_auditoria,fecha_utc,usuario_app_id,motivo,(clave_registro->>'id')::integer AS id_medicamento,
 coalesce((datos_anteriores->>'stock')::integer,0) AS stock_anterior,
 coalesce((datos_nuevos->>'stock')::integer,0) AS stock_nuevo,
 coalesce((datos_nuevos->>'stock')::integer,0)-coalesce((datos_anteriores->>'stock')::integer,0) AS variacion
FROM auditoria WHERE tabla='medicamento' AND operacion<>'DELETE';
CREATE VIEW vw_ventas_descuadradas AS
SELECT v.id,v.total,coalesce(sum(d.cantidad*d.precio_unitario),0) AS total_detalle
FROM venta v LEFT JOIN detalle_venta d ON d.id_venta=v.id
GROUP BY v.id,v.total HAVING v.total<>coalesce(sum(d.cantidad*d.precio_unitario),0);

REVOKE ALL ON SCHEMA farmacia FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA farmacia FROM PUBLIC;
DO $$ DECLARE r text; BEGIN
 FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP
 IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r) THEN
 EXECUTE format('REVOKE ALL ON SCHEMA farmacia FROM %I',r);
 EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA farmacia FROM %I',r);
 END IF; END LOOP;
END $$;
COMMIT;
